<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameSoundboard.Core\GameSoundboard.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
    <PackageReference Include="NAudio.Vorbis" Version="3.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
